config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  root 'definitions#index'

  resources :definitions do
    collection do
      get :search
    end
  end

end

app/models/definition.rb
class Definition < ActiveRecord::Base
  validates :word, presence: true, uniqueness: true
  validates :meaning, presence: true

  attachment :profile_image, type: :image

  def self.search(search)
    where("word like ? or meaning like ?", "%#{search}%", "%#{search}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:github]

  def self.from_omniauth(auth)
    user = where(provider: auth['provider'], uid: auth['uid']).first_or_create

    user.name         = auth.info.name
    user.email        = auth.info.email
    user.nickname     = auth.info.nickname
    user.access_token = auth.credentials.token
    user.password     = Devise.friendly_token[0,20]
    user.save!

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/definitions_controller.rb
class DefinitionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_definition, only: [:show, :edit, :update, :destroy]

  # GET /definitions
  # GET /definitions.json
  def index
    @definitions = Definition.all
  end

  # GET /definitions/1
  # GET /definitions/1.json
  def show
  end

  def search
    @search = params[:q]
    @definitions = Definition.search(@search)
  end

  # GET /definitions/new
  def new
    @definition = Definition.new
  end

  # GET /definitions/1/edit
  def edit
  end

  # POST /definitions
  # POST /definitions.json
  def create
    @definition = Definition.new(definition_params)

    respond_to do |format|
      if @definition.save
        format.html { redirect_to @definition, notice: 'Definition was successfully created.' }
        format.json { render :show, status: :created, location: @definition }
      else
        format.html { render :new }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /definitions/1
  # PATCH/PUT /definitions/1.json
  def update
    @book = Definition.find(params[:id])

    respond_to do |format|
      if @definition.update(definition_params)
        format.html { redirect_to @definition, notice: 'Definition was successfully updated.' }
        format.json { render :show, status: :ok, location: @definition }
      else
        format.html { render :edit }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /definitions/1
  # DELETE /definitions/1.json
  def destroy
    @definition.destroy
    respond_to do |format|
      format.html { redirect_to definitions_url, notice: 'Definition was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_definition
    @definition = Definition.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def definition_params
    params.require(:definition).permit(:word, :meaning, :word_type, :profile_image)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/definitions_helper.rb
module DefinitionsHelper
end

app/views/definitions/_definition.html.erb
<tr>
  <td><%= definition.word %></td>
  <td><%= definition.word_type %></td>
  <td><%= definition.meaning %></td>
  <td class="table-button-cell"><%= button_to 'Display', definition, class: "btn btn-sm btn-default cell_padding square_corners", method: :get %></td>
  <td class="table-button-cell"><%= button_to 'Edit', edit_definition_path(definition), class: "btn btn-sm btn-default cell_padding square_corners", method: :get %></td>
  <td class="table-button-cell"><%= button_to 'Delete', definition, method: :delete, class: "btn btn-sm btn-danger cell_padding square_corners", data: { confirm: 'Are you sure you want to delete this definition?' } %></td>
</tr>

app/views/definitions/_form.html.erb
<%= form_for(@definition, class: "form-horizontal") do |f| %>
  <% if @definition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@definition.errors.count, "error") %> prohibited this definition from being saved:</h2>

      <ul>
      <% @definition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <%= f.label :word %><br>
    <%= f.text_field :word, class: "form_control" %>
  </div>
  <div class="field">
    <%= f.label :word_type %><br>
    <%= f.text_field :word_type, class: "form_control" %>
  </div>
  <div class="field">
    <%= f.label :meaning %><br>
    <%= f.text_area :meaning, class: "form_control" %>
  </div>
  <div class="field">
    <%= f.label :profile_image %><br>
    <%= f.attachment_field :profile_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/definitions/_search_header.html.erb
<% if @search %>
  <h4>Search results for <%= @search %></h4>
  <h5>Found <%= pluralize(@definitions.count, "definition") %></h5>
<% end %>

app/views/definitions/edit.html.erb
<div class="container">
  <div class="page-header">
    <h4>Editing Definition</h4>

    <%= render 'form' %>

    <%= link_to 'Show', @definition %> |
    <%= link_to 'Back', definitions_path %>
  </div>
</div>

app/views/definitions/index.html.erb
<div class="page-header">
 <%= button_to 'New Word', new_definition_path, class: "btn btn-sm btn-success square_corners", method: :get %>
 <div id='search-header'>
   <%= render 'search_header' %>
  </div>
  <table class="table table-condensed table-hover">
    <thead>
      <tr>
        <th>Word</th>
        <th>Type</th>
        <th>Meaning</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody id="definition_list">
      <%= render @definitions %>
    </tbody>
  </table>
  <p>
  <% if @search %>
    Back to <%= link_to 'Home', definitions_path %>
  <% end %>
  <p>
</div>

app/views/definitions/new.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th><h4>New Definition</h4></th>
    </tr>
  </thead>
<tbody>
  <tr>
    <td><%= render 'form' %></td>
  </tr>
  <tr>
    <td>Back to <%= link_to 'Home', definitions_path %></td>
  </tr>
</tbody>
</table>

app/views/definitions/search.js.erb
$('#definition_list').html('<%= escape_javascript(render @definitions) %>');
$('#search-header').html('<%= escape_javascript(render 'search_header') %>');

app/views/definitions/show.html.erb
<div class="page-header">
  <p>
    <%= image_tag attachment_url(@definition, :profile_image, :fill, 200, 200, fallback: "default.png") %>
  </p>
  <p>
    <strong>Word:</strong>
    <%= @definition.word %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= @definition.word_type %>
  </p>

  <p>
    <strong>Meaning:</strong>
    <%= @definition.meaning %>
  </p>
</div>

<%= link_to 'Edit', edit_definition_path(@definition) %> |
<%= link_to 'Back', definitions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Byron's Rails Dictionary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse square_corners" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="nav navbar-nav">
        <h4 class="navbar-text navbar-left">Byron's Rails Dictionary</h4>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', definitions_path %></li>
        <%- if current_user.nil? %>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end -%>
        <% if current_user %>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
        <%= yield :more_links %>
      </ul>
      <div class="navbar-form navbar-left">
        <%= form_tag search_definitions_path, remote: true, method: :get do %>
            <div class="form-group">
          <%= search_field_tag :q, "", class: "form-control btn-sm square_corners", placeholder: "Search" %>
          <%= submit_tag "Submit", class: "btn btn-sm btn-default square_corners" %>
            </div>
        <% end %>
      </div>
      <p class="navbar-text navbar-right current_user">
        <% if current_user %>
        Logged in as <a href="#" class="navbar-link"><%= current_user.email %></a>
        <% end %>
      </p>
    </div>
  </div>
</nav>
  <div class="content">
    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>
    <%= yield %>
  </div>

  <nav class="navbar navbar-default navbar-fixed-bottom footer">
  <div class="container-fluid">
    <a href="#">Links</a> | <a href="#">Contact Us</a>
  </div>
</nav>
</body>
</html>